### ISSUE TITLE
Github Actions Labeler not working

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/awesome-semantic-search#37]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Agrover112/awesome-semantic-search/issues) before creating one.

**Describe the bug**
There seems to be an issue with Github token. Giving HTTP error. Refer the actions tab for more details

**Comment by radiantly** [comment]
Hi, I could work on this issue, but the labeler action requires a `.github/labeler.yml` file specifying what labels to apply depending on the file paths that have changed (refer [actions/labeler](https://github.com/actions/labeler)). This will need to be added first before we can make full use of the labeler action.

To fix the HTTP error, we can switch to `pull_request_target` from `pull_request` so that the passed token has adequate permissions.

**Comment by Agrover112** [comment]
Sure @radiantly  I will assign you!
